name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: clone main repository
        uses: actions/checkout@v2
      - name: clone submodule (stake)
        uses: actions/checkout@v2
        with:
          repository: starlay-finance/starlay-stake
          path: starlay-stake
          ref: v2
          ssh-key: ${{ secrets.SSH_KEY_SUBMODULE_STAKE }}
          persist-credentials: false
      - name: clone submodule (stake)
        uses: actions/checkout@v2
        with:
          repository: starlay-finance/starlay-protocol
          path: starlay-protocol
          ref: v2
          ssh-key: ${{ secrets.SSH_KEY_SUBMODULE_PROTOCOL }}
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Test
        run: npm run test
      - name: Coverage
        run: npm run coverage
      #- uses: codecov/codecov-action@v1
      #  with:
      #    fail_ci_if_error: true
