name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      SUBMODULE_STAKE_TOKEN: ${{ secrets.SSH_KEY_SUBMODULE_STAKE }}
      SUBMODULE_PROTOCOL_TOKEN: ${{ secrets.SSH_KEY_SUBMODULE_PROTOCOL }}

    steps:
      - name: clone main repository
        uses: actions/checkout@v2
      - name: clone submodules
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "$SUBMODULE_STAKE_TOKEN" > $HOME/.ssh/id_rsa
          sudo chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"
          git submodule update --init submodule-stake
          echo -e "$SUBMODULE_PROTOCOL_TOKEN" > $HOME/.ssh/id_rsa
          sudo chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"
          git submodule update --init submodule-protocol
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Test
        run: npm run test
      - name: Coverage
        run: npm run coverage
      #- uses: codecov/codecov-action@v1
      #  with:
      #    fail_ci_if_error: true
